#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/compose
- name: Copy docker-compose file
  copy:
    src: ../../compose.yml
    dest: /home/ubuntu/compose.yml

- name: Run compose
  community.docker.docker_compose:
    project_src: /home/ubuntu
    state: present